### ISSUE TITLE
ArrayType::containsValueByValueCallback returns FALSE for NULL values

### ISSUE THREAD

**Issue by hubipe** [consistence/consistence#19]
ArrayType::containsValueByValueCallback returns FALSE, when callback returns TRUE for NULL value. This snippet is searching for NULL value in array. It should return TRUE, but FALSE is returned instead.

```php
$arr = [1, 2, 3, NULL, 5, 6, 7];
$result = ArrayType::containsValueByValueCallback($arr, function ($value) {
	return $value === NULL;
});
var_dump($result); // dumps FALSE
```

**Comment by VasekPurchart** [comment]
Hello, thanks for the report, I didn't realize this situation when implementing it. Revealed a few other cases thanks to this :) You can see the PR that fixes it here: #21.

Fix released as [1.0.2](https://github.com/consistence/consistence/releases/tag/1.0.2)
